services:
  eureka:
    image: maven:3.9.9-eclipse-temurin-17
    working_dir: /workspace
    volumes:
      - ./eureka:/workspace
      - maven-cache:/root/.m2
    command: mvn spring-boot:run
    ports:
      - "8761:8761"

  api-gateway:
    image: maven:3.9.9-eclipse-temurin-17
    working_dir: /workspace
    volumes:
      - ./api-gateway:/workspace
      - maven-cache:/root/.m2
    command: mvn spring-boot:run
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
    depends_on:
      - eureka
    ports:
      - "9090:9090"

  hospital-backend-user:
    image: maven:3.9.9-eclipse-temurin-17
    working_dir: /workspace
    volumes:
      - ./hospital-backend-user:/workspace
      - maven-cache:/root/.m2
    command: mvn spring-boot:run
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
    depends_on:
      - eureka
    ports:
      - "8080:8080"

  doctor:
    image: maven:3.9.9-eclipse-temurin-17
    working_dir: /workspace
    volumes:
      - ./doctor:/workspace
      - maven-cache:/root/.m2
    command: mvn spring-boot:run
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
    depends_on:
      - eureka
    ports:
      - "8081:8081"

  patient:
    image: maven:3.9.9-eclipse-temurin-17
    working_dir: /workspace
    volumes:
      - ./patient:/workspace
      - maven-cache:/root/.m2
    command: mvn spring-boot:run
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
    depends_on:
      - eureka
    ports:
      - "8082:8082"

  pharmacy:
    image: maven:3.9.9-eclipse-temurin-17
    working_dir: /workspace
    volumes:
      - ./pharmacy:/workspace
      - maven-cache:/root/.m2
    command: mvn spring-boot:run
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
    depends_on:
      - eureka
    ports:
      - "8083:8083"

volumes:
  maven-cache:
